# Generated by Django 3.0.3 on 2020-07-26 09:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import timeline.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=1500)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('gallery', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=timeline.models.moment_gallery_path)),
                ('type', models.CharField(choices=[('i', 'Image'), ('v', 'Video')], max_length=25)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Moment')),
            ],
        ),
    ]
