# Generated by Django 3.0.3 on 2020-07-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moment',
            name='gallery',
        ),
    ]
