# Generated by Django 3.1.5 on 2021-01-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='date',
        ),
    ]
