# Generated by Django 3.2.5 on 2022-05-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20210118_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
